version: '3.6'

services:
  filebot:
    build:
      context: ./service
      dockerfile: Dockerfile
    image: asperitus/filebot:latest
    restart: always
    container_name: filebot
    hostname: filebot
    ports:
      - "18080:8080"
    networks:
      web:

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: asperitus/filebot-ui:latest
    restart: always
    volumes:
      - ./ui/src:/app/src
      - ./ui/public:/app/public
    working_dir: /app
    container_name: frontend
    hostname: frontend
    ports:
      - "13000:3000"
    command: "yarn start"
    networks:
      web:

networks:
  web:
    external: false
    name: web